### ISSUE TITLE
关于NYCTAXI_OD数据集的相关问题

### ISSUE THREAD

**Issue by WYbjtu** [LibCity/Bigscity-LibCity#199]
百度云中NYCTAXI202004-202006数据集的NYCTAXI202004-202006.od文件中显示This file is too big, please connect the author.请问下这个文件需要在哪里下载
希望能得到您的帮助

**Comment by aptx1231** [comment]
已经把数据集上传到云盘中，请重新下载所有文件即可。其中.od文件以.zip压缩后上传的。
另外，也可以使用我们发布的数据处理[脚本](https://github.com/LibCity/Bigscity-LibCity-Datasets/blob/master/nyctaxi_od.py)，下载原始的NYCTaxi数据集即可自定义处理哪几个月的数据了。
