### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './raw_data/NYCTaxi20140112/NYCTaxi20140112.dyna'

### ISSUE THREAD

**Issue by TronYY** [LibCity/Bigscity-LibCity#205]
这个dyna有些数据集没有  是应该怎么生成

**Comment by aptx1231** [comment]
这个是网格数据，不存在.dyna文件。猜测可能在使用Graph-based的模型运行Grid-based的数据，建议参考这个链接中的Note:
https://bigscity-libcity-docs.readthedocs.io/en/latest/user_guide/data/dataset_for_task.html

**Comment by TronYY** [comment]
我以为是这个数据集你们还没处理过，
https://github.com/LibCity/Bigscity-LibCity-Datasets

因为里面提到 Here we present the statistics of the datasets we have processed.  列表里面并没有NYCTaxi20140112，然后让我们用转换工具自己转换

**Comment by aptx1231** [comment]
因为NYCTaxi20140112是其他人处理过的数据集，我们提供了脚步可以将它变成我们的原子文件，但是没有放在List里，因为是别人的数据集。我们提供了NYCTAXI_GRID可以从原始的轨迹数据，来统计网格的流量。

**Comment by aptx1231** [comment]
也可以用我们的[工具](https://github.com/LibCity/Bigscity-LibCity-Datasets/blob/master/nyctaxi20140112.py)来进行转换，输出的s是.grid文件。想要用Graph-based的模型运行此数据集，请[参考](https://bigscity-libcity-docs.readthedocs.io/en/latest/user_guide/data/dataset_for_task.html)的Note。
