### ISSUE TITLE
GEML，数据格式错误

### ISSUE THREAD

**Issue by gonglucky** [LibCity/Bigscity-LibCity#214]
您好，我用你们提供的处理好的数据“NYCTAXI202004-202006_OD”运行GEML模型发生错误。
命令行为：python run_model.py --task traffic_state_pred --model GEML --dataset NYCTAXI202004-202006_OD。
一开始提示错误为 No such file or directory: './raw_data/NYCTAXI202004-202006_OD/NYCTAXI202004-202006_OD.rel'。
然后我将文件中NYCTAXI202004-202006.rel 文件改为 NYCTAXI202004-202006_OD.rel 运行。
“- INFO - Loading file NYCTAXI202004-202006.od”时又发生错误：KeyError: "['inflow', 'outflow'] not in index"
请问这个模型使用哪个数据集运行？是数据集的问题还是代码的问题？

**Comment by l782993610** [comment]
用 `python predict.py 其他参数 --dataset NYCTAXI202004-202006` 就可以。
数据集里的 config 文件有一点问题，以下是正确的。这个 ['inflow', 'outflow'] 表示数据集里这两列是特征数据，但实际上只有一列 flow，主要就是改了这里。
```
{
 "geo": {
  "including_types": [
   "Polygon"
  ],
  "Polygon": {}
 },
 "od": {
  "including_types": [
   "state"
  ],
  "state": {
   "origin_id": "geo_id",
   "destination_id": "geo_id",
   "flow": "num"
  }
 },
 "info": {
  "data_col": [
   "flow"
  ],
  "data_files": [
   "NYCTAXI202004-202006"
  ],
  "geo_file": "NYCTAXI202004-202006",
  "output_dim": 2,
  "init_weight_inf_or_zero": "inf",
  "set_weight_link_or_dist": "dist",
  "calculate_weight_adj": false,
  "weight_adj_epsilon": 0.1,
  "time_intervals": 3600
 }
}
```

另外，注意原论文作者没有开放数据集，适当调参。

**Comment by l782993610** [comment]
查阅了一下 Dataset 仓库代码，处理脚本已经修正过了一次，主要是之前缓存的结果没有修正。

**Comment by aptx1231** [comment]
【上边的回复有一点问题】
是这样的，这个问题出现在config.json文件，这个文件之前的处理有点问题，目前云盘中的最新版文件已经是正确的了，您可能是之前下载的数据。只要您重新获取config.json文件即可，运行命令为`python run_model.py --model GEML --dataset NYCTAXI202004-202006_OD`。
您也可以直接复制下边的json文件：
```
{
 "geo": {
  "including_types": [
   "Polygon"
  ],
  "Polygon": {}
 },
 "od": {
  "including_types": [
   "state"
  ],
  "state": {
   "origin_id": "geo_id",
   "destination_id": "geo_id",
   "flow": "num"
  }
 },
 "info": {
  "data_col": [
   "flow"
  ],
  "data_files": [
   "NYCTAXI202004-202006"
  ],
  "geo_file": "NYCTAXI202004-202006",
  "rel_file": "NYCTAXI202004-202006",
  "output_dim": 1,
  "init_weight_inf_or_zero": "inf",
  "set_weight_link_or_dist": "dist",
  "calculate_weight_adj": true,
  "weight_adj_epsilon": 0.1,
  "time_intervals": 3600
 }
}
```

**Comment by gonglucky** [comment]
明白了，是config中数据描述和数据不一致。
请问 nyctaxi_od.py 脚本中 
location = json.load(open(input_dir_flow + '/taxi_zones_final.json', 'r'))    taxi_zones_final.json文件在哪儿获取。

**Comment by aptx1231** [comment]
这里解释一下几个参数：
dataset：数据集的文件夹名字
geo_file：文件夹里边的geo文件的文件名
rel_file：文件夹里边的rel文件的文件名
data_files：文件夹里边的dyna文件的文件名，可以是列表
data_col： dyna文件中想要使用的列名，这个数据集是flow

**Comment by aptx1231** [comment]
taxi_zones_final.json已经传到github仓库里边了
