### ISSUE TITLE
请问可以添加一下多GPU训练模块吗

### ISSUE THREAD

**Issue by Neoyanghc** [LibCity/Bigscity-LibCity#215]
目前好像只能一块卡训练，能不能你们把这个需求集成处理一下，自己一个个加太麻烦了，感谢

**Comment by WenMellors** [comment]
感谢您的意见，我们这边着手加一下。

**Comment by TronYY** [comment]
> 感谢您的意见，我们这边着手加一下。

这个要怎么加啊

**Comment by WenMellors** [comment]
您好，其实情况是这样的：目前开发的首要目标还是新增复现模型，这边目前分不出人来搞这个。我自己之前也没有过多卡训练的经验。很难帮助到您。

**Comment by Neoyanghc** [comment]
好的，辛苦您们了

**Comment by aptx1231** [comment]
我这边试了一下torch.nn.DataParallel来进行多GPU运算，但是目前在我们的结构下存在一定的问题。
我们定义的Batch结构（本质上是字典）不适合这个DataParallel的操作，如果是直接用torch原生的Dataset，那么是可以支持多G[U的，但是目前的Batch结构统一了全部的模型输入，也限制了这一点。
之后我们会考虑看有没有其他办法实现多GPU训练，目前我们的实验环境为2080ti，单卡的显存足够，如果您的显存不够可以尝试减小batch_size。

**Comment by Neoyanghc** [comment]
谢谢，但是减少batch-size 又会让模型容易过拟合，希望有时间可以排期一下，感恩
