### ISSUE TITLE
CSTN 的NYC_TOD数据集里时间没有显示吗    test集的数据是从中截取吗  截取多少

### ISSUE THREAD

**Issue by TronYY** [LibCity/Bigscity-LibCity#218]
如题

**Comment by l782993610** [comment]
是的，[CSTN 论文](https://github.com/liulingbo918/CSTN)作者处理数据集的时候就没有留下时间戳了。测试集也是从整个数据集切出来的，具体的大小根据 dataset 配置文件的 train_rate，eval_rate 参数确定（1-train_rate-eval_rate 就是测试集大小）
