### ISSUE TITLE
TAXIBJ dataset

### ISSUE THREAD

**Issue by wuzhe71** [LibCity/Bigscity-LibCity#228]
It seems that some files are missing when i run STDN model with TAXIBJ dataset:
`FileNotFoundError: [Errno 2] No such file or directory: './raw_data/TAXIBJ/TAXIBJ2013.gridod'`

**Comment by aptx1231** [comment]
You can see our [docs](https://bigscity-libcity-docs.readthedocs.io/en/latest/user_guide/data/dataset_for_task.html), this model must need a 'gridod' file, which is the od-flow between grids.  You can try our recommended dataset NYCBike20160708 & NYCTaxi20150103.
