### ISSUE TITLE
max_epoch如何进行更改？

### ISSUE THREAD

**Issue by sly111** [LibCity/Bigscity-LibCity#252]
在'task_config.json'确定待运行模型的执行器为TrafficStateExecutor，于是在在'TrafficStateExecutor.json'将"max_epoch": 1000更改为1000以后，发现实验过程中max_epoch仍为100，请问如何更改相关参数改变max_epoch呀？

**Comment by NickHan-cs** [comment]
您可以参考我们的文档https://bigscity-libcity-docs.readthedocs.io/en/latest/user_guide/config_settings.html，我们的参数服从一定的优先级：命令行参数>用户定义配置文件>模型所在模块默认参数>其它模块默认参数，您在executor模块中更换了max_epoch，但是可能模型模块默认的max_epoch还是100，所以建议您可以修改模型模块的max_epoch参数或者在命令行参数种传入max_epoch。
