### ISSUE TITLE
CARA模型不存在对应的evaluator配置

### ISSUE THREAD

**Issue by Qwtdgh** [LibCity/Bigscity-LibCity#256]
轨迹下一跳任务中的CARA模型   在task_config.json中指定"evaluator": "CARALocPredEvaluator"
但是config/evaluator中不包含**CARALocPreEvaluator.json**文件。
可能要添加CARALocPreEvaluator.json。

**Comment by aptx1231** [comment]
@WenMellors

**Comment by WenMellors** [comment]
测试后，会与 #257 一起修复。
