### ISSUE TITLE
MPR

### ISSUE THREAD

**Issue by nadiaaaaachen** [LibCity/Bigscity-LibCity#268]
有两个问题：
1、在处理最后以每个点为终点的转移概率矩阵的时候，需要用到马尔科夫链 𝑉 = 𝐷 + 𝑄 ⋅ 𝐷 + 𝑄2 ⋅ 𝐷 + ⋅⋅⋅ + 𝑄𝑡−1 ⋅ 𝐷 因为用的矩阵是稀疏矩阵 所以乘法的复杂度有O2 而且通常需要sys.MAXSIZE的乘方 感觉不太跑得动 不知如何处理
2、在聚类处理后很多轨迹会出现重复的情况 比如原来轨迹是1 2 3 4 聚类以后1 3 变成1个点了 轨迹就变成1 2 1 4了 前两步相当于无效轨迹 最终测试集量准确度的时候会有很大的误差 但如果去重又会毁坏轨迹数据的真实性

**Comment by WenMellors** [comment]
现在聚类后的图是多少个点呀？第二个问题感觉是聚类效果不太好的原因，是现在聚类的参数设得比较紧的原因吗？

**Comment by nadiaaaaachen** [comment]
1000+个点 用的是原参数 感觉确实少了点 改一下参数的话可以聚到8000+个点 但是感觉更跑不动了
