### ISSUE TITLE
CSTN 数据集不一致问题

### ISSUE THREAD

**Issue by asja-aaa** [LibCity/Bigscity-LibCity#270]
我发现您在百度网盘提供的CSTN数据版本 落后于您在Bigscity-LibCity-Datasets脚本生成的数据  因为我发现这俩者数据不一致 显然新脚本生产的数据才是较为准备的  但是我也发现了一些其他问题 
![image](https://user-images.githubusercontent.com/52391237/160622389-6276e5e1-3d51-4e6f-b01b-ca5b041cc7bd.png)
我发现row_id 与col_id 在定义与存储的时候好像错位了  但我不知道究竟是哪一个在前  希望能得到您的帮助

**Comment by asja-aaa** [comment]
还有destination 都写成列了

**Comment by aptx1231** [comment]
@l782993610
