### ISSUE TITLE
自动化调参报错，程序密码不对，redis设置为无密码。程序的密码设置？

### ISSUE THREAD

**Issue by ZPFPHD** [LibCity/Bigscity-LibCity#276]
Traceback (most recent call last):
  File "E:\conda\envs\pytorch\lib\site-packages\ray\_private\services.py", line 655, in wait_for_redis_to_start
    redis_client.client_list()
  File "E:\conda\envs\pytorch\lib\site-packages\redis\client.py", line 1194, in client_list
    return self.execute_command('CLIENT LIST')
  File "E:\conda\envs\pytorch\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 567, in connect
    self.on_connect()
  File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 484, in read_response
    raise response
redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hyper_tune.py", line 52, in <module>
    other_args=other_args)
  File "H:\Bigscity-LibCity\libcity\pipeline\pipeline.py", line 211, in hyper_parameter
    local_dir='./libcity/cache/hyper_tune', num_samples=num_samples)
  File "E:\conda\envs\pytorch\lib\site-packages\ray\tune\tune.py", line 298, in run
    _ray_auto_init()
  File "E:\conda\envs\pytorch\lib\site-packages\ray\tune\tune.py", line 681, in _ray_auto_init
    ray.init()
  File "E:\conda\envs\pytorch\lib\site-packages\ray\_private\client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "E:\conda\envs\pytorch\lib\site-packages\ray\worker.py", line 896, in init
    ray_params=ray_params)
  File "E:\conda\envs\pytorch\lib\site-packages\ray\node.py", line 248, in __init__
    self.start_head_processes()
  File "E:\conda\envs\pytorch\lib\site-packages\ray\node.py", line 894, in start_head_processes
    self.start_redis()
  File "E:\conda\envs\pytorch\lib\site-packages\ray\node.py", line 714, in start_redis
    port_denylist=self._ray_params.reserved_ports)
  File "E:\conda\envs\pytorch\lib\site-packages\ray\_private\services.py", line 881, in start_redis
    port_denylist=port_denylist)
  File "E:\conda\envs\pytorch\lib\site-packages\ray\_private\services.py", line 1029, in _start_redis_instance
    wait_for_redis_to_start("127.0.0.1", port, password=password)
  File "E:\conda\envs\pytorch\lib\site-packages\ray\_private\services.py", line 666, in wait_for_redis_to_start
    redis_ip_address, redis_port)) from authEx
RuntimeError: Unable to connect to Redis at 127.0.0.1:6379.

**Comment by aptx1231** [comment]
你好，可以运行最新的master分支上关于自动调参的代码，如果还是有问题的话，请提供详细的运行环境、运行命令、参数搜索json文件等便于我们查看。

**Comment by ZPFPHD** [comment]
运行命令：
python hyper_tune.py --task traffic_state_pred --model GRU --dataset METR_LA --space_file sample_space_file --exp_id 36322
参数搜索json：
{
    "learning_rate": {
        "type": "choice",
        "list": [0.01, 0.005, 0.001]
    },
    "max_epoch": {
        "type": "randint",
        "lower": 2,
        "upper": 10
    },
    "hidden_size": {
    	"type": "choice",
    	"list": [50, 100, 200, 500]
    },
    "dropout": {
    	"type": "uniform",
    	"lower": 0.1,
    	"upper": 0.6
    }
} 
运行环境：（python3.7）
Package                       Version
----------------------------- -----------
absl-py                       0.13.0
aiohttp                       3.7.4.post0
aioredis                      1.3.1
alabaster                     0.7.12
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
ase                           3.22.1
astor                         0.8.1
astunparse                    1.6.3
async-timeout                 3.0.1
atomicwrites                  1.4.0
attrs                         21.2.0
Babel                         2.9.1
backcall                      0.2.0
bleach                        4.1.0
blinker                       1.4
boto                          2.49.0
boto3                         1.21.32
botocore                      1.24.32
Bottleneck                    1.3.2
brotlipy                      0.7.0
bz2file                       0.98
cachetools                    4.2.2
certifi                       2021.10.8
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.3
cloudpickle                   2.0.0
colorama                      0.4.4
coverage                      5.5
cryptography                  3.4.8
cycler                        0.10.0
Cython                        0.29.24
d2l                           0.17.3
debugpy                       1.5.1
decorator                     4.4.2
defusedxml                    0.7.1
dgl                           0.6.1
docutils                      0.17.1
durbango                      0.23
entrypoints                   0.3
et-xmlfile                    1.1.0
fastdtw                       0.3.4
fastprogress                  1.0.0
filelock                      3.6.0
flake8                        4.0.1
flake8-polyfill               1.0.2
fonttools                     4.25.0
fsspec                        2022.1.0
funcy                         1.17
future                        0.18.2
gast                          0.3.3
gensim                        4.1.2
geographiclib                 1.52
geopy                         2.0.0
google-auth                   1.33.0
google-auth-oauthlib          0.4.1
google-pasta                  0.2.0
googledrivedownloader         0.4
grpcio                        1.36.1
h5py                          2.10.0
hiredis                       1.1.0
hyperopt                      0.2.5
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.8.1
importlib-resources           5.4.0
iniconfig                     1.1.1
ipykernel                     6.7.0
ipython                       7.31.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
isodate                       0.6.1
jedi                          0.18.1
Jinja2                        3.0.3
jmespath                      0.10.0
joblib                        1.1.0
JsonForm                      0.0.2
jsonschema                    4.4.0
JsonSir                       0.0.2
jupyter                       1.0.0
jupyter-client                7.1.1
jupyter-console               6.4.0
jupyter-core                  4.9.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.2
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
kiwisolver                    1.3.1
llvmlite                      0.37.0
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.3
mccabe                        0.7.0
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mock                          4.0.3
more-itertools                8.12.0
msgpack                       1.0.2
multidict                     5.1.0
munkres                       1.1.4
nbclient                      0.5.11
nbconvert                     6.4.2
nbformat                      5.1.3
nest-asyncio                  1.5.4
networkx                      2.6.3
nltk                          3.7
notebook                      6.4.8
numba                         0.54.1
numexpr                       2.7.3
numpy                         1.21.5
oauthlib                      3.1.1
olefile                       0.46
openpyxl                      3.0.9
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.3.5
pandocfilters                 1.5.0
parso                         0.8.3
patsy                         0.5.2
pep8-naming                   0.12.1
pickle5                       0.0.11
pickleshare                   0.7.5
Pillow                        8.4.0
pip                           21.2.4
pluggy                        0.13.1
prettytable                   3.0.0
prometheus-client             0.13.1
prompt-toolkit                3.0.24
protobuf                      3.17.2
psutil                        5.8.0
py                            1.10.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.8.0
pycparser                     2.21
pyDeprecate                   0.3.1
pyflakes                      2.4.0
pygcn                         0.1
Pygments                      2.11.2
PyJWT                         2.1.0
pyOpenSSL                     21.0.0
pyparsing                     3.0.4
pyreadline                    2.1
pyrsistent                    0.18.1
PySocks                       1.7.1
pytest                        6.2.4
python-dateutil               2.8.2
Python-EasyConfig             0.1.7
python-louvain                0.15
python-utils                  2.5.6
pytorch-lightning             1.5.9
pytz                          2021.3
pywin32                       302
pywinpty                      2.0.2
PyYAML                        6.0
pyzmq                         22.3.0
qtconsole                     5.2.2
QtPy                          2.0.1
ray                           1.6.0
rdflib                        6.1.1
redis                         3.5.3
regex                         2022.3.15
requests                      2.27.1
requests-oauthlib             1.3.0
Resource                      0.2.1
rsa                           4.7.2
s3transfer                    0.5.0
scikit-learn                  1.0.1
scipy                         1.7.1
seaborn                       0.11.2
Send2Trash                    1.8.0
setproctitle                  1.1.10
setuptools                    59.5.0
six                           1.16.0
smart-open                    1.9.0
snowballstemmer               2.2.0
Sphinx                        4.3.2
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
statsmodels                   0.13.0
tables                        3.5.2
tabulate                      0.8.9
tensorboard                   2.6.0
tensorboard-data-server       0.6.0
tensorboard-plugin-wit        1.6.0
tensorboardX                  2.2
tensorflow                    2.3.0
tensorflow-estimator          2.6.0
termcolor                     1.1.0
terminado                     0.13.1
testpath                      0.5.0
threadpoolctl                 2.2.0
toml                          0.10.2
torch                         1.10.0
torch-cluster                 1.5.9
torch-geometric               2.0.3
torch-geometric-temporal      0.50.0
torch-scatter                 2.0.9
torch-sparse                  0.6.12
torch-spline-conv             1.2.1
torchaudio                    0.10.0
torchmetrics                  0.7.1
torchsummary                  1.5.1
torchtext                     0.11.0
torchvision                   0.11.1
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.1
typing-extensions             3.10.0.2
urllib3                       1.26.7
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.0.2
wheel                         0.37.0
widgetsnbextension            3.5.2
win-inet-pton                 1.1.0
wincertstore                  0.2
wrapt                         1.12.1
xlwings                       0.24.9
yacs                          0.1.8
yarl                          1.6.3
zipp                          3.6.0

**Comment by WenMellors** [comment]
1. 我们 [requirements.txt](https://github.com/LibCity/Bigscity-LibCity/blob/master/requirements.txt) 中给出的 ray 版本是 1.2.0。ray 相关依赖包 idna 版本是 2.10，不确定是否是版本的问题。

> python中设置了验证密码

2. 另外，关于这一点我们并无设置，不知道是不是 ray 第三方库的问题，或者是 windows 防火墙相关问题。
在 [ray tune issue#8023](https://github.com/ray-project/ray/issues/8023) 中找到了与您相关的报错。

**Comment by aptx1231** [comment]
我在windows10, python=3.7，具体环境如下，没有出现这个问题。

Package                       Version
----------------------------- ------------
absl-py                       0.14.1
aiohttp                       3.7.4.post0
aiohttp-cors                  0.7.0
aioredis                      2.0.0
alabaster                     0.7.12
analytics-python              1.4.0
anyio                         3.5.0
asgiref                       3.5.0
async-timeout                 3.0.1
attrs                         21.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backoff                       1.10.0
bcrypt                        3.2.0
blessings                     1.7
branca                        0.4.2
brotlipy                      0.7.0
cached-property               1.5.2
cachetools                    4.2.4
certifi                       2021.10.8
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.8
click                         8.0.3
click-plugins                 1.1.1
cligj                         0.7.2
cloudpickle                   2.0.0
colorama                      0.4.4
colorful                      0.5.4
commonmark                    0.9.1
cryptography                  36.0.0
cycler                        0.11.0
Cython                        0.29.21
datasets                      1.2.1
debugpy                       1.5.1
decorator                     4.4.2
dgl                           0.6.1
dill                          0.3.4
docutils                      0.16
entrypoints                   0.4
fastapi                       0.75.0
fastdtw                       0.3.4
ffmpy                         0.3.0
filelock                      3.3.0
Fiona                         1.8.13.post1
flake8                        3.3.0
folium                        0.12.1.post1
fonttools                     4.28.3
future                        0.18.2
GDAL                          3.0.2
gensim                        4.0.1
geographiclib                 1.52
geopandas                     0.10.2
geopy                         2.0.0
google-api-core               2.1.0
google-auth                   1.35.0
google-auth-oauthlib          0.4.6
googleapis-common-protos      1.53.0
gpustat                       0.6.0
gradio                        2.8.14
grpcio                        1.41.0
h11                           0.13.0
h5py                          3.6.0
huggingface-hub               0.2.1
hyperopt                      0.2.5
idna                          3.2
imagesize                     1.2.0
importlib-metadata            4.8.1
ipykernel                     6.9.2
ipython                       7.29.0
jedi                          0.18.0
Jinja2                        3.0.3
joblib                        1.1.0
jsonschema                    4.1.0
jupyter-client                7.1.2
jupyter-core                  4.9.2
kiwisolver                    1.3.2
linkify-it-py                 1.0.3
loguru                        0.6.0
mapclassify                   2.4.3
Markdown                      3.3.4
markdown-it-py                2.0.1
MarkupSafe                    2.0.1
matplotlib                    3.5.0
matplotlib-inline             0.1.2
mccabe                        0.6.1
mdit-py-plugins               0.3.0
mdurl                         0.1.0
mkl-fft                       1.3.0
mkl-random                    1.2.2
mkl-service                   2.4.0
monotonic                     1.6
msgpack                       1.0.2
multidict                     5.2.0
multiprocess                  0.70.12.2
munch                         2.5.0
munkres                       1.1.4
nest-asyncio                  1.5.4
networkx                      2.5.1
nltk                          3.2.4
numpy                         1.19.4
nvidia-ml-py3                 7.352.0
oauthlib                      3.1.1
olefile                       0.46
opencensus                    0.8.0
opencensus-context            0.1.2
orjson                        3.6.7
packaging                     21.3
pandas                        1.1.5
paramiko                      2.10.3
parso                         0.8.2
patsy                         0.5.2
pep8-naming                   0.4.1
pickleshare                   0.7.5
Pillow                        8.3.1
pip                           21.2.4
prettytable                   2.1.0
prometheus-client             0.11.0
prompt-toolkit                3.0.20
protobuf                      3.18.1
psutil                        5.9.0
py                            1.10.0
py-spy                        0.3.10
pyarrow                       7.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.3.1
pycparser                     2.21
pycryptodome                  3.14.1
pydantic                      1.9.0
pydub                         0.25.1
pyflakes                      1.5.0
Pygments                      2.6.1
PyNaCl                        1.5.0
pyOpenSSL                     21.0.0
pyparsing                     3.0.6
pyproj                        2.6.1.post1
pyrsistent                    0.18.0
pyshp                         2.1.3
PySocks                       1.7.1
pytest                        3.2.1
python-dateutil               2.8.2
python-multipart              0.0.5
pytz                          2021.3
pywin32                       303
PyYAML                        5.4.1
pyzmq                         22.3.0
ray                           1.2.0
recommonmark                  0.7.1
redis                         3.5.3
regex                         2021.11.10
requests                      2.26.0
requests-oauthlib             1.3.0
rsa                           4.7.2
Rtree                         0.9.7
sacremoses                    0.0.46
scikit-learn                  0.24.0
scipy                         1.5.3
sentencepiece                 0.1.96
setuptools                    49.3.0
Shapely                       1.7.1
six                           1.16.0
smart-open                    5.2.1
sniffio                       1.2.0
snowballstemmer               2.1.0
Sphinx                        3.3.1
sphinx-markdown-tables        0.0.15
sphinx-rtd-theme              0.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
starlette                     0.17.1
statsmodels                   0.11.0
tabulate                      0.8.9
tensorboard                   2.4.1
tensorboard-plugin-wit        1.8.0
tensorboardX                  2.2
threadpoolctl                 3.0.0
tokenizers                    0.9.4
toml                          0.10.2
torch                         1.7.1
torchaudio                    0.7.2
torchtext                     0.6.0
torchvision                   0.8.2
tornado                       6.1
tqdm                          4.60.0
traitlets                     5.1.1
transformers                  4.2.1
typing-extensions             3.10.0.2
uc-micro-py                   1.0.1
unicodedata2                  13.0.0.post2
urllib3                       1.26.7
uvicorn                       0.17.6
wcwidth                       0.2.5
Werkzeug                      2.0.2
wheel                         0.37.0
win-inet-pton                 1.1.0
win32-setctime                1.1.0
wincertstore                  0.2
xlrd                          2.0.1
xlutils                       2.0.0
xlwt                          1.3.0
xxhash                        3.0.0
xyzservices                   2021.11.0
yarl                          1.7.0
zipp                          3.6.0

**Comment by ZPFPHD** [comment]
该问题还未解决，目前想到的方法是给redis-cli中执行设置密码，请问在自动调参程序中哪里可以设置传递密码？

**Comment by ZPFPHD** [comment]
"""
模型调参脚本 (based on the hyperopt)
"""

import argparse
import random



from libcity.pipeline import objective_function
from libcity.executor import HyperTuning
from libcity.utils import str2bool, get_logger, set_random_seed, add_general_args

#from ray.util.client import ray#####

if __name__ == '__main__':

#    ray.init(_redis_password="123456")####
    parser = argparse.ArgumentParser()
    # 增加指定的参数
    parser.add_argument('--task', type=str,
                        default='traffic_state_pred', help='the name of task')
    parser.add_argument('--model', type=str,
                        default='GRU', help='the name of model')
    parser.add_argument('--dataset', type=str,
                        default='METR_LA', help='the name of dataset')
    parser.add_argument('--config_file', type=str,
                        default=None, help='the file name of config file')
    parser.add_argument('--saved_model', type=str2bool,
                        default=True, help='whether save the trained model')
    parser.add_argument('--train', type=str2bool, default=True,
                        help='whether re-train model if the model is \
                             trained before')
    parser.add_argument('--params_file', type=str,
                        default='hyper_example.txt', help='the file which specify the \
                             hyper-parameters and ranges to be adjusted')
    parser.add_argument('--hyper_algo', type=str,
                        default='grid_search', help='hyper-parameters search algorithm')
    parser.add_argument('--max_evals', type=int,
                        default=100, help='Allow up to this many function \
                             evaluations before returning.')
    parser.add_argument('--exp_id', type=str, default=None, help='id of experiment')
    parser.add_argument('--seed', type=int, default=0, help='random seed')
    **parser.add_argument('-a', type=str, dest='123456', action='store', help='password of redis ')**###########
    # 增加其他可选的参数
    add_general_args(parser)
    # 解析参数
    args = parser.parse_args()
    dict_args = vars(args)
    other_args = {key: val for key, val in dict_args.items() if key not in [
        'task', 'model', 'dataset', 'config_file', 'saved_model', 'train',
        'params_file', 'hyper_algo'] and val is not None}
    # exp_id
    exp_id = dict_args.get('exp_id', None)
    if exp_id is None:
        # Make a new experiment ID
        exp_id = int(random.SystemRandom().random() * 100000)
        other_args['exp_id'] = exp_id
    # logger
    logger = get_logger({'model': args.model, 'dataset': args.dataset, 'exp_id': exp_id})
    # seed
    seed = dict_args.get('seed', 0)
    set_random_seed(seed)
    other_args['seed'] = seed
    hp = HyperTuning(objective_function, params_file=args.params_file, algo=args.hyper_algo,
                     max_evals=args.max_evals, task=args.task, model_name=args.model,
                     dataset_name=args.dataset, config_file=args.config_file,
                     saved_model=args.saved_model, train=args.train, other_args=other_args)
    hp.start()
    hp.save_result(filename='hyper.result')
    logger.info('best params: ' + str(hp.best_params))
    logger.info('best result: ')
    logger.info(str(hp.params2result[hp.params2str(hp.best_params)]))

**Comment by ZPFPHD** [comment]
"""
模型调参脚本 (based on the hyperopt)
"""

import argparse
import random



from libcity.pipeline import objective_function
from libcity.executor import HyperTuning
from libcity.utils import str2bool, get_logger, set_random_seed, add_general_args

#from ray.util.client import ray#####

if __name__ == '__main__':

#    ray.init(_redis_password="123456")####
    parser = argparse.ArgumentParser()
    # 增加指定的参数
    parser.add_argument('--task', type=str,
                        default='traffic_state_pred', help='the name of task')
    parser.add_argument('--model', type=str,
                        default='GRU', help='the name of model')
    parser.add_argument('--dataset', type=str,
                        default='METR_LA', help='the name of dataset')
    parser.add_argument('--config_file', type=str,
                        default=None, help='the file name of config file')
    parser.add_argument('--saved_model', type=str2bool,
                        default=True, help='whether save the trained model')
    parser.add_argument('--train', type=str2bool, default=True,
                        help='whether re-train model if the model is \
                             trained before')
    parser.add_argument('--params_file', type=str,
                        default='hyper_example.txt', help='the file which specify the \
                             hyper-parameters and ranges to be adjusted')
    parser.add_argument('--hyper_algo', type=str,
                        default='grid_search', help='hyper-parameters search algorithm')
    parser.add_argument('--max_evals', type=int,
                        default=100, help='Allow up to this many function \
                             evaluations before returning.')
    parser.add_argument('--exp_id', type=str, default=None, help='id of experiment')
    parser.add_argument('--seed', type=int, default=0, help='random seed')
    parser.add_argument('-a', type=str, dest='123456', action='store', help='password of redis ')###########
    # 增加其他可选的参数
    add_general_args(parser)
    # 解析参数
    args = parser.parse_args()
    dict_args = vars(args)
    other_args = {key: val for key, val in dict_args.items() if key not in [
        'task', 'model', 'dataset', 'config_file', 'saved_model', 'train',
        'params_file', 'hyper_algo'] and val is not None}
    # exp_id
    exp_id = dict_args.get('exp_id', None)
    if exp_id is None:
        # Make a new experiment ID
        exp_id = int(random.SystemRandom().random() * 100000)
        other_args['exp_id'] = exp_id
    # logger
    logger = get_logger({'model': args.model, 'dataset': args.dataset, 'exp_id': exp_id})
    # seed
    seed = dict_args.get('seed', 0)
    set_random_seed(seed)
    other_args['seed'] = seed
    hp = HyperTuning(objective_function, params_file=args.params_file, algo=args.hyper_algo,
                     max_evals=args.max_evals, task=args.task, model_name=args.model,
                     dataset_name=args.dataset, config_file=args.config_file,
                     saved_model=args.saved_model, train=args.train, other_args=other_args)
    hp.start()
    hp.save_result(filename='hyper.result')
    logger.info('best params: ' + str(hp.best_params))
    logger.info('best result: ')
    logger.info(str(hp.params2result[hp.params2str(hp.best_params)]))
我在run-hyper中增加了密码传递参数，不知道是否正确

**Comment by aptx1231** [comment]
ray的版本问题已经修复了吗？
而且昨天说的是hyper_tune.py运行出错，现在是变成run_hyper.py运行出错了吗？

**Comment by aptx1231** [comment]
我们建议使用我们规定的版本，如果不能使用我们要求的环境，请直接到[ray](https://github.com/ray-project/ray)的开发者的仓库反馈问题。

**Comment by ZPFPHD** [comment]
我使用了ray 1.2.0，但是还出现这个报错，redis未设置密码时，提示客户端有身份验证，应该将python程序去掉。当我设置redis密码时候，提示无效密码，应该是python中设置的密码未正确传入。
是hyper_tune,我搞错成了run_hyper.
按照教程在终端输入的优化参数的指令后面了实验的ID
python hyper_tune.py --task traffic_state_pred --model GRU --dataset METR_LA --space_file sample_space_file --exp_id 36322

**Comment by aptx1231** [comment]
windows还是linux

**Comment by ZPFPHD** [comment]
win10

**Comment by aptx1231** [comment]
这边确实复现不出来，我们对ray也并不熟悉，非常抱歉。
如果确实需要自动调参，可以使用run_hyper.py，基于hyperopt库，更简单一些。

**Comment by ZPFPHD** [comment]
好的，你们的软件已经非常棒了。希望越办越好，更加有影响力
