### ISSUE TITLE
ETA数据集错误

### ISSUE THREAD

**Issue by fly2008begin** [LibCity/Bigscity-LibCity#279]
从百度云盘上下载的数据集Chengdu_Taxi_Sample1 和Beijing_Taxi_Sample 无法使用，前者缺失geo文件，后者Error tokenizing data. C error: EOF inside string starting at row 92677

**Comment by aptx1231** [comment]
您可以确认一下这两个数据集是否是最新版的数据，我们在4.21修改过一次。
![image](https://user-images.githubusercontent.com/35984903/165703789-9300d0ee-0822-44c9-a0f3-98d88440b1fb.png)
如果确认无误的话，请注意由于模型所需要的特征不一样，所以模型运行的数据集有限制，具体参考:
![image](https://user-images.githubusercontent.com/35984903/165704002-d404e1d8-f20a-4195-a329-08b706c79bcd.png)
如果依旧确认无误的话，请再反馈给我们，谢谢！
