### ISSUE TITLE
Grid-OD数据问题

### ISSUE THREAD

**Issue by aptx1231** [LibCity/Bigscity-LibCity#282]
代码中对于gridod数据的处理方法如下：
![image](https://user-images.githubusercontent.com/35984903/166153967-d198b35c-83b8-4476-81ef-9112ba6f4699.png)
代码位置：libcity/data/dataset/traffic_state_grid_od_dataset.py里边的`_load_grid_od_6d`和`_load_grid_od_4d`。

他的这个遍历顺序是起点行、列，终点行、列，然后直接取整个len_time长度的数据进行赋值。但是现在的gridod数据格式如下：
![image](https://user-images.githubusercontent.com/35984903/166153913-5c6d4f7e-12a4-44d6-a11e-20ceb91295f8.png)
按照现在的代码读进来的数据是错误的。现在数据读取的代码对于所有的数据都是统一的（先行后列、先起点后终点），所以数据集需要修复一下。 @l782993610

**Comment by l782993610** [comment]
fixed
