### ISSUE TITLE
Multi_Graph_Demand Dataset中config文件未放入

### ISSUE THREAD

**Issue by davechenxy** [LibCity/Bigscity-LibCity#283]
看了一下其他dataset里基本都有config.json文件，但MGD这个dataset的不知道是不是漏放了

**Comment by aptx1231** [comment]
内容如下：

{
  "geo": {
    "including_types": [
      "Point"
    ],
    "Point": {}
  },
  "rel": {
    "including_types": [
      "geo"
    ],
    "geo": {
      "distance": "num",
      "connection": "num",
      "similarity": "num"
    }
  },
  "dyna": {
    "including_types": [
      "state"
    ],
    "state": {
      "entity_id": "geo_id",
      "demand": "num"
    }
  },
  "info": {
    "data_col": [
      "demand"
    ],
    "data_files": [
      "Multi_Graph_Demand"
    ],
    "geo_file": "Multi_Graph_Demand",
    "rel_file": "Multi_Graph_Demand",
    "output_dim": 1,
    "time_intervals": 300,
    "init_weight_inf_or_zero": "zero",
    "set_weight_link_or_dist": "dist",
    "calculate_weight_adj": true,
    "weight_adj_epsilon": 0.1
  }
}

您可以先自己新建一个config.json文件，之后我们会更新到网盘中。

**Comment by aptx1231** [comment]
网盘也已经更新了。

**Comment by davechenxy** [comment]
感谢回复
