### ISSUE TITLE
作者您好，我在使用Graph wavenet的模型训练后，将evaluate_cache的npz导出为xlsx，但是真实值出现了问题。

### ISSUE THREAD

**Issue by ZPFPHD** [LibCity/Bigscity-LibCity#290]
作者您好，我在使用Graph wavenet的模型训练后，将evaluate_cache的npz导出为xlsx，但是真实值出现了问题。其中导出的12个xlsx文件，这12个xlsx文件的真实值完全不同，都跟我的raw_data中的真实值不同，不知道哪里出了问题。您方便的时候回答一下，十分感谢！

**Comment by aptx1231** [comment]
不太清楚是如何把npz导出成xlsx，但是输出预测结果是12步，如果是每一步导出一个xlsx，那12步的真值确实是不一样的。

**Comment by ZPFPHD** [comment]
请问一下，这个12代表的预测输出步长12步？还是前12个最佳模型？我是把它作为前12个最佳模型导出了12个表，对应这12个模型的预测输出

**Comment by aptx1231** [comment]
只有1个模型，没有12个模型，12 是预测步长

**Comment by ZPFPHD** [comment]
好的，谢谢。怪不得
