### ISSUE TITLE
conflict issues

### ISSUE THREAD

**Issue by Onedean** [LibCity/Bigscity-LibCity#295]
Nice work!!!

I tried to run quick start according to the readme, but found the following error:

```
TypeError: Descriptors cannot not be created directly. If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0. If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

This seems to conflict with the package ‘ray’, here is my solution:
```
pip uninstall protobuf
pip install protobuf==3.20.1
```

In addition, do you have a plan to support single machine-multi card and multi machine-multi card ?

**Comment by aptx1231** [comment]
Thanks for your feedback, it may be that some update to the ray package caused it to have to rely on a lower version of protobuf.
Sorry, at the moment, single multi-card and multi-card multi-card support is out of our planning scope, you can refer to [DistributedDataParallel](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html) for development.
