### ISSUE TITLE
How to train STResNet model on dataset PEMSD4/PEMSD8?

### ISSUE THREAD

**Issue by dourgey** [LibCity/Bigscity-LibCity#299]
Hi, I try to train STResNet model on the datasets of PEMSD4 and PEMSD8 for the traffic flow prediction task, however, there are some error during the training process. It seems like that STResNet model training doesn't support the point data like PEMSD4/PEMSD8 yet. How could I train the STResNet model on the dataset PEMSD4/PEMSD8 ？

**Comment by aptx1231** [comment]
STResNet can not be used on dataset PEMSD4/PEMSD8, because it uses CNN to model the data, i.e., needing a grid-based dataset.
