### ISSUE TITLE
foursquare_sin dataset

### ISSUE THREAD

**Issue by Veneziahhh** [LibCity/Bigscity-LibCity#318]
Hello there, I found that in your google drive, there are only foursquare_nyc and foursquare_tky dataset, but I want to use foursquare_sin(singapore) as well in order to complete my research. Please kindly upload foursquare_sin dataset and I would appreciate it.

**Comment by WenMellors** [comment]
Sorry, we cannot provide the `foursquare_sin`. Our Foursquare data is obtained from [Dingqi YANG Foursquare](https://sites.google.com/site/yangdingqi/home/foursquare-dataset#h.p_ID_46). So we actually do not have the source data of singapore. If you have the source data, you can refer to [Bigscity-LibCity-Datasets/foursquare.py](https://github.com/LibCity/Bigscity-LibCity-Datasets/blob/master/foursquare.py) to preprocess the data into atomic file format in LibCity.
