### ISSUE TITLE
Something seems dismatch in PEMS07 dataset

### ISSUE THREAD

**Issue by SUSTCLHC** [LibCity/Bigscity-LibCity#319]
Hi, thanks for your work on LibCity.
When checking the dataset, I found the PEMS07 actually has data for only 98 days. However, many works including LibCity claims that it contains data for 123 days (5/1/2017 - 8/31/2017), which confuses me. Can you give specific instructions on that?
Thanks again.

**Comment by aptx1231** [comment]
感谢提醒，我调研了一下。

Pems07数据集最早由论文STSGCN[1]的作者提供，代码链接[在这](https://github.com/Davidham3/STSGCN)。
该论文中提到时间范围是123 days (5/1/2017 - 8/31/2017)，而代码仓库中提供的数据npz文件其实只有98天，我猜测大家引用此数据集的时候直接遵循STSGCN论文中提供的表格数据，而没有真实的考虑过数据到底有多少天（我们就是这样，所以造成了天数的误报）。不过大家用的数据应该都是同样的98天的数据。具体原因只能像原作者提问了，谢谢！

[1]Spatial-Temporal Synchronous Graph Convolutional Networks: A New Framework for Spatial-Temporal Network Data Forecasting
