### ISSUE TITLE
Why do geographical embedding and semantical embedding share the GCN parameters in GEML?

### ISSUE THREAD

**Issue by Ao-Last** [LibCity/Bigscity-LibCity#322]
According to the paper, geographical embedding and semantical embedding are trained through two sperate networks. 
But ge and se are generated using the same GCN module in your implementation `libcity/model/traffic_od_prediction`
![Snipaste_2022-12-04_20-47-49](https://user-images.githubusercontent.com/63785048/205491329-d9f9968a-cc7f-4f68-b479-ac150c0d5e99.png)

**Comment by aptx1231** [comment]
@l782993610

**Comment by l782993610** [comment]
You are right, thank you. It's  fixed in pr #323
