### ISSUE TITLE
我在运行你们的交通轨迹预测任务的时候出现的问题

### ISSUE THREAD

**Issue by JoelEmbiiddddd** [LibCity/Bigscity-LibCity#330]
用Foursquare_tky数据集来运行你们其他这个任务下的模型全部都出现错误， 要么就是最后的准确率为0，要么就是比其他文章中相同的baseline高出一倍，比如我用DeepMove来预测，得到的Recall@1为0.562，但其他文章中的值正确应为0.173左右

**Comment by JoelEmbiiddddd** [comment]
噢，不，我测试了好几个模型以及数据集，以及重新git新的文件得到的结果都出现较大的错误并且和其他文章得到的结果有很大的出入。应该就是Next-location prediction这个任务下有问题代码有问题

**Comment by JoelEmbiiddddd** [comment]
![image](https://user-images.githubusercontent.com/86511606/222916319-295dfed6-a3c8-4680-be01-a62954ce0d91.png)
以及测试的过程中，存在的另一个问题就是，使用不同的Metric，最终得到的结果都是一样的

**Comment by WenMellors** [comment]
您好，初步判断是数据集的问题。因为我们最开始使用的是[Dingqi Yang 开源的 Foursquare Global 版本的数据集](https://sites.google.com/site/yangdingqi/home/foursquare-dataset#h.p_ID_56)，后来我们替换为了[Dingqi Yang 开源的 Foursquare TKY 和 NYC 版本的数据集](https://sites.google.com/site/yangdingqi/home/foursquare-dataset#h.p_ID_46)。因为我们的欠考虑，没有在这个版本的数据集上去做一个测试。

问题便出在这个新版本的数据集用户的 POI 定位时间间隔太大了，这就导致了我们数据处理部分做轨迹切割的时候（trajectory_dataset.cutter_filter 函数）大部分轨迹都被筛除了。因为我们默认会删除长度小于 5 的轨迹，和轨迹数小于 2 的用户。最终结果就是，用于模型训练和测试的数据很少（POI 点很少以及用户数目很少），这应该导致整个预测任务的难度大幅降低。

我们正在考虑是否要重新使用 Global 版本的数据源（在这里我们从 Global 的 Check-in 数据中筛选出了 TKY 和 NYC 的 Check-in 数据）。而且 DeepMove 的论文中说的数据版本也不是 [Dingqi Yang 开源的任何一个版本](https://sites.google.com/site/yangdingqi/home/foursquare-dataset)

**Comment by JoelEmbiiddddd** [comment]
噢，确实，你们也可以对使用这两个数据集的时候不调用trajectory_dataset.cutter_filter 函数，因为我们在复现的时候实验还是有很多要参考这两个数据集。然后再弄一个Global版本的。

挺好的，这个tool也挺好用的，如果你们更新好了记得踢我一下，我好可以继续进行实验

**Comment by WenMellors** [comment]
我又检查了一下 [Dingqi Yang 开源的 Foursquare TKY 和 NYC 版本的数据集](https://sites.google.com/site/yangdingqi/home/foursquare-dataset#h.p_ID_46)。我发现了问题所在：在处理 TKY 的时候，错误的没有对 check-in 数据按照时间顺序排序，这导致了后面筛选后的数据太少了。我已经重新排序了，现在正在重新测试 DeepMove 在 Foursquare-TKY 上的性能。

在其他数据集上，会有类似的问题吗？

**Comment by JoelEmbiiddddd** [comment]
应该不止是tky，nyc同样在一些模型上不work，比如图中展示的STRNN
![image](https://user-images.githubusercontent.com/86511606/222949662-e2e7da8b-a1ef-40da-b046-4df5ab368934.png)

**Comment by JoelEmbiiddddd** [comment]
以及STAN模型，在切割数据环节的时候，我们服务器运行往往需要10个小时才完成数据切割，然后跑一个epoch大概需要40多分钟，不知道是不是我们服务器的问题，显卡是3090

**Comment by WenMellors** [comment]
了解

**Comment by JoelEmbiiddddd** [comment]
![image](https://user-images.githubusercontent.com/86511606/223007050-5a8099d7-f543-40eb-bfb0-f7fac613da2a.png)
SERM在使用foursquare_nyc的时候也报错了，如果有时间的话也请您看看

**Comment by WenMellors** [comment]
在 #331 中， SERM 模型的报错修复了。然后 Foursquare-NYC 数据集更新了，解决了排序问题。现在在 Foursquare-TKY 上的验证结果应该比较可信了：以下是 DeepMove 和 SERM 两个模型在 Foursquare-NYC 上的实验结果
  | Precision@5 | Recall@5 | F1-score@5 | MRR@5 | MAP@5 | NDCG@5
-- | -- | -- | -- | -- | -- | --
SERM | 0.0548 | 0.2740 | 0.0913 | 0.1807 | 0.1807 | 0.2040
DeepMove | 0.0653 | 0.3264 | 0.1088 | 0.2141 | 0.2141 | 0.2421

需要注意的是，轨迹下一跳实验对比结果与对轨迹数据的预处理操作密切相关。如果不保证模型的数据预处理操作相同，那么我认为实验结果将不具有说服力，这也是我们为什么要做 LibCity 的原因。

上述实验的预处理操作的参数设置为(用户自定义 config 配置文件)：
```json
{
    "topk": 5,
    "metrics": ["Precision", "Recall", "F1", "MRR", "MAP", "NDCG"],
    "min_sessions": 2,
    "min_checkins": 0,
    "min_session_len": 3,
    "window_size": 72,
    "max_session_len": 50
}
```

另外，关于为什么轨迹下一跳预测需要对 POI 轨迹数据进行切割与筛选操作。我的观点是：由于 POI check-in 数据本质不是一条轨迹，因此领域中常规的做法就是按照某种划分方式，将用户的某一部分 check-in 记录视作一次出行下产生的（即 POI 轨迹）。在实现 LibCity 的过程中，我总结了三种领域中有研究在用的划分方式：按照 check-in 记录之间的时间间隔划分（最常用）、同一天的 check-in 记录视作一条轨迹、固定条数的 check-in 组成一条轨迹（STAN 使用）。而我们实现的轨迹数据的筛选方法同样是领域中常用的筛选方法，即删除过短或过长的轨迹、删除轨迹数少的用户。**这些预处理操作会很容易影响实验结果。**

**Comment by WenMellors** [comment]
另外，关于 ST-RNN 模型，该模型没有开源代码，我们参考论文复现后性能一直比较差。可以参考 Github 上还有[其他人](https://github.com/yongqyu/STRNN)复现了 ST-RNN，其性能一样的差。

**Comment by JoelEmbiiddddd** [comment]
已重新测试，可以，很好，满意，满分，给赞！这效率可以！

**Comment by WenMellors** [comment]
1. Foursquare 等 POI check-in 数据集，本质就不是 GPS 轨迹。这一点可以参见 [Foursquare 开源数据集介绍](http://www-public.it-sudparis.eu/~zhang_da/pub/dataset_TSMC2014_readme.txt)
> This dataset includes long-term (about 10 months) check-in data in New York city and Tokyo collected from Foursquare from 12 April 2012 to 16 February 2013.
> It contains two files in tsv format. Each file contains 8 columns, which are:
> 1. User ID (anonymized)
> 2. Venue ID (Foursquare)
> 3. Venue category ID (Foursquare)
> 4. Venue category name (Fousquare)
> 5. Latitude
> 6. Longitude
> 7. Timezone offset in minutes (The offset in minutes between when this check-in occurred and the same time in UTC)
> 8. UTC time
即是说每个 check-in 都绑定一个 Venue ID （POI ID）。
2.  如果你是询问的 cutter_filter 函数处理后缓存的 json 文件的话，这里缓存的结果的结构如下：
```python
    def cutter_filter(self):
        """
        切割后的轨迹存储格式: (dict)
            {
                uid: [
                    [
                        checkin_record,
                        checkin_record,
                        ...
                    ],
                    [
                        checkin_record,
                        checkin_record,
                        ...
                    ],
                    ...
                ],
                ...
            }
        """
```
checkin_record 就是 .dyna 文件中记录的 check-in 记录。这里是粗暴的将他放入了（可能会占用大量内存）。

**Comment by JoelEmbiiddddd** [comment]
对，我询问的是 cutter_filter 函数处理后缓存的 json 文件的话，整体的代码我都过了一遍，就是想问一下，原数据集中不是有Latitude，Longitude，但是你们转化后就变成了  {0：[324142, "trajectory", "2013-02-14T15:52:53Z", 0, 735]}。

我把关于TrajectoryLocation相关的Datasets代码都过了一遍，都没有找到你们是如何处理Latitude和Longitude的，那么我就怀疑说 最后一个数字“735”是你们将地图进行网格后给予的网格ID号。 所以你们的切割后的数据格式是不是这样子：

0：用户ID
324142： Checks-in的序列Index
“trajectory” ： 数据类型
"2013-02-14T15:52:53Z" ： 时间
0 ： 用户ID
735： 将经纬度映射所在的网格ID号，用网格ID号代替原有的经纬度

**Comment by JoelEmbiiddddd** [comment]
还是里边的735代表的是POI 的ID？

**Comment by WenMellors** [comment]
是 POI ID

**Comment by JoelEmbiiddddd** [comment]
好的好的，谢谢

**Comment by WenMellors** [comment]
因为既然是 POI 数据集，那么我们认为 check-in 的 GPS 就是 POI 附近的 GPS。我们用这些 GPS 信息来推算了 POI 的经纬度坐标。数据处理的代码是在 [Dataset](https://github.com/LibCity/Bigscity-LibCity-Datasets/blob/master/foursquare.py) 另一个仓库。

**Comment by JoelEmbiiddddd** [comment]
嗯嗯，感谢你的回复，你已经回答了我所有疑惑，万分感激！祝你顺利，paper多多
