### ISSUE TITLE
How to generate atomic files from a new dataset?

### ISSUE THREAD

**Issue by SuhanG17** [LibCity/Bigscity-LibCity#333]
I am working on a project with datasets not included in the LibCity library, and I wish to use this framework to compare models' performance. I am aware that datasets and adjacency matrices should be transformed to the form of [atomic files](https://bigscity-libcity-docs.readthedocs.io/en/latest/user_guide/data/atomic_files.html). However, I need help locating how this repo generates these files. Could you inform me where I should find these codes? Your help would be much appreciated!

**Comment by aptx1231** [comment]
You can refer to the script we use to process existing open source datasets: https://github.com/LibCity/Bigscity-LibCity-Datasets. Also refer to the description of the atomic file format, https://bigscity-libcity-docs. readthedocs.io/en/latest/user_guide/data/atomic_files.html.

**Comment by SuhanG17** [comment]
Found it, Thank you!
