### ISSUE TITLE
运行DeepTTE模型出现下面情况

### ISSUE THREAD

**Issue by xiaozhangyongqin** [LibCity/Bigscity-LibCity#340]
![image](https://github.com/LibCity/Bigscity-LibCity/assets/100301654/2daee39b-ef31-4558-a8ac-1fe5b0a38893)
你好，我想请问一下这个问题：
它显示已杀死，我使用内存是32G 我感觉完全够用 ，因为我跑第一个例子模型!python run_model.py --task traffic_state_pred --model GRU --dataset METR_LA --gpu_id -1是没有问题的，跑DeepTTE模型的时候就出现这个问题，我不太清楚为什么，我把数据集砍半之后还是这个情况，谢谢！

**Comment by aptx1231** [comment]
deeptte运行哪一个数据集呢，应该是内存不够，才会出现Killed。
可以运行的同时使用htop命令观测一下内存的占用。

**Comment by xiaozhangyongqin** [comment]
使用的是Chengdu_Taxi_Sample1 这个数据集

**Comment by xiaozhangyongqin** [comment]
> deeptte运行哪一个数据集呢，应该是内存不够，才会出现Killed。 可以运行的同时使用htop命令观测一下内存的占用。
是的 占用百分百 就kill了  参数量太大了 跑不起来 我再切分一下数据集试试，感谢

**Comment by zhangjiayux** [comment]
> 使用的是Chengdu_Taxi_Sample1 这个数据集

你好，你现在还有成都和北京的数据集吗

**Comment by xiaozhangyongqin** [comment]
> > 使用的是Chengdu_Taxi_Sample1 这个数据集
> 
> 你好，你现在还有成都和北京的数据集吗

没有，我用的是作者给的部分数据集，实际上需要更全的数据

**Comment by zhangjiayux** [comment]
> > > 使用的是Chengdu_Taxi_Sample1 这个数据集
> > 
> > 
> > 你好，你现在还有成都和北京的数据集吗
> 
> 没有，我用的是作者给的部分数据集，实际上需要更全的数据

https://duke.box.com/s/ni5ca8iktneq828fk5cul8afwkvszkdr这是论文作者提供的完整数据集，但是现在不能用了

**Comment by xiaozhangyongqin** [comment]
> > > > 使用的是Chengdu_Taxi_Sample1 这个数据集
> > > 
> > > 
> > > 你好，你现在还有成都和北京的数据集吗
> > 
> > 
> > 没有，我用的是作者给的部分数据集，实际上需要更全的数据
> 
> [https://duke.box.com/s/ni5ca8iktneq828fk5cul8afwkvszkdr这是论文作者提供的完整数据集，但是现在不能用了](https://duke.box.com/s/ni5ca8iktneq828fk5cul8afwkvszkdr%E8%BF%99%E6%98%AF%E8%AE%BA%E6%96%87%E4%BD%9C%E8%80%85%E6%8F%90%E4%BE%9B%E7%9A%84%E5%AE%8C%E6%95%B4%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E4%BD%86%E6%98%AF%E7%8E%B0%E5%9C%A8%E4%B8%8D%E8%83%BD%E7%94%A8%E4%BA%86)

你可以问问作者，有没有备份数据集，我这里我忘记了，不好意思哈

**Comment by zhangjiayux** [comment]
> > > > > 使用的是Chengdu_Taxi_Sample1 这个数据集
> > > > 
> > > > 
> > > > 你好，你现在还有成都和北京的数据集吗
> > > 
> > > 
> > > 没有，我用的是作者给的部分数据集，实际上需要更全的数据
> > 
> > 
> > [https://duke.box.com/s/ni5ca8iktneq828fk5cul8afwkvszkdr这是论文作者提供的完整数据集，但是现在不能用了](https://duke.box.com/s/ni5ca8iktneq828fk5cul8afwkvszkdr%E8%BF%99%E6%98%AF%E8%AE%BA%E6%96%87%E4%BD%9C%E8%80%85%E6%8F%90%E4%BE%9B%E7%9A%84%E5%AE%8C%E6%95%B4%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E4%BD%86%E6%98%AF%E7%8E%B0%E5%9C%A8%E4%B8%8D%E8%83%BD%E7%94%A8%E4%BA%86)
> 
> 你可以问问作者，有没有备份数据集，我这里我忘记了，不好意思哈

好的，谢谢啦
