### ISSUE TITLE
在运行已复现模型的时候遇到如下问题

### ISSUE THREAD

**Issue by qixingyu-code** [LibCity/Bigscity-LibCity#342]
Traceback (most recent call last):
  File "/root/autodl-tmp/Bigscity-LibCity/libcity/data/utils.py", line 21, in get_dataset
    return getattr(importlib.import_module('libcity.data.dataset'),
AttributeError: module 'libcity.data.dataset' has no attribute 'ASTGCNDataset'

**Comment by aptx1231** [comment]
是运行什么命令出现的问题呢？麻烦提供一下

**Comment by qixingyu-code** [comment]
python run_model.py --task traffic_state_pred --dataset PeMS04 --model ASTGCN --max_epoch 2
我尝试去使用经典的数据集测试模型的性能，输入命令后就出现之前描述的错误。不知道是什么原因，希望您能解答一下

**Comment by aptx1231** [comment]
PeMS04 数据集是在哪下载的？网盘下载的应该是PEMSD4

**Comment by aptx1231** [comment]
如果是从PDFormer仓库下载的话，需要改一下名字，因为这个代码做了一个名字的验证。

![image](https://github.com/LibCity/Bigscity-LibCity/assets/35984903/20fafc9c-f0f6-43aa-bc78-fb22a6b7c826)

**Comment by qixingyu-code** [comment]
我的数据集是在LibCity系统的github主页提供的百度网盘下载的，刚刚尝试了一下命令行将数据集名称更换为PEMSD4，但是还是出现了报错，不知道是什么原因导致的
命令行输入 python run_model.py --task traffic_state_pred --dataset PEMSD4 --model ASTGCN
![SQ734PVVEY17A3I9XYL75PE](https://github.com/LibCity/Bigscity-LibCity/assets/112141409/c9bdc425-74a8-4785-9136-35ad4a3e8172)
![2${PY8Y5HI}RSBC 1~(D~}Q](https://github.com/LibCity/Bigscity-LibCity/assets/112141409/2a23c275-7b4f-404d-9770-da1fdf6b9a88)
由于终端显示的信息有点多，我依次对提示进行截取

**Comment by aptx1231** [comment]
raw_data/目录下边的内容看一下

**Comment by qixingyu-code** [comment]
![JGF(722XCL2 9)WIUBGYJQ](https://github.com/LibCity/Bigscity-LibCity/assets/112141409/2792a0aa-9591-4a78-825c-04ac1968605f)
我对raw_data目录的部分数据集(PEMS系统的)进行截取

**Comment by aptx1231** [comment]
百度网盘里边就是PEMSD4呀
![image](https://github.com/LibCity/Bigscity-LibCity/assets/35984903/2746015f-1ab8-470f-ad4f-532e1fb1a366)


PEMSD4/下边的内容呢，也看一下，是这个吗？

![image](https://github.com/LibCity/Bigscity-LibCity/assets/35984903/8b0f7b5a-1e10-4005-8fbe-182e5d128774)

**Comment by qixingyu-code** [comment]
![LE2~0K9D9Y}@D(AREXCZN~W](https://github.com/LibCity/Bigscity-LibCity/assets/112141409/17a0c3e5-65d5-4dbf-a817-d9e906e6622f)
感觉好像没问题啊，为啥我运行总是有bug啊，23333

**Comment by aptx1231** [comment]
看你第二张图的报错，应该是gensim的版本问题

**Comment by qixingyu-code** [comment]
好的，那我再好好调试一下环境，非常感谢您对我问题的解答
