### ISSUE TITLE
复现地图匹配STMatching时出现以下问题

### ISSUE THREAD

**Issue by LyPluss** [LibCity/Bigscity-LibCity#343]
您好，我在复现地图匹配的STMatching模型时，程序跑了一个下午，还是处于begin map matching阶段，这是正常情况吗？[捂脸]
![image](https://github.com/LibCity/Bigscity-LibCity/assets/97956775/0392f725-2ac8-4b52-a72c-9694c980c5dc)

**Comment by aptx1231** [comment]
感觉是正常的，你要不试一下global数据集里边的数据，比较小。
这个seattle数据集太大了。

**Comment by LyPluss** [comment]
嗯嗯，换成了HMMM模型，跑了3个小时，出结果了，我换另一个数据集再试试。

**Comment by aptx1231** [comment]
如果你需要高效的mm匹配效率的话，推荐用一些c++实现的库。这个是用python实现的比较慢。
比如：fmm, https://fmm-wiki.github.io/
