### ISSUE TITLE
关于传统模型

### ISSUE THREAD

**Issue by OvOYu** [LibCity/Bigscity-LibCity#356]
![image](https://github.com/LibCity/Bigscity-LibCity/assets/107761563/c13005b7-d3a0-49d7-b354-b08b4074df8a)
我修改了16行的名称yiji以及29行的路径，我在windows环境下运行，结果显示MAPE是inf，请问是哪里出现了问题呢

**Comment by aptx1231** [comment]
没问题，因为label有0， mape就是inf



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Beyond ***@***.***&gt;
发送时间: 2023年9月8日 20:51
收件人: LibCity/Bigscity-LibCity ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [LibCity/Bigscity-LibCity] 关于传统模型 (Issue #356)





 

 我修改了16行的名称yiji以及29行的路径，我在windows环境下运行，结果显示MAPE是inf，请问是哪里出现了问题呢

**Comment by OvOYu** [comment]
谢谢您的回复！
![image](https://github.com/LibCity/Bigscity-LibCity/assets/107761563/87ee3538-76c5-4362-92da-75969bdddf10)
SVR的这个正常吗，数据集为PEMSD4，但是我发现80多的MAE高于其他论文报告的很多了

**Comment by aptx1231** [comment]
传统模型可能得挑挑配置，效果一般都比较差



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Beyond ***@***.***&gt;
发送时间: 2023年9月9日 08:47
收件人: LibCity/Bigscity-LibCity ***@***.***&gt;
抄送: Jiawei Jiang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [LibCity/Bigscity-LibCity] 关于传统模型 (Issue #356)





 
谢谢您的回复！
 
 SVR的这个正常吗，数据集为PEMSD4，但是我发现80多的MAE高于其他论文报告的很多了

**Comment by OvOYu** [comment]
谢谢您，祝好！

**Comment by TronYY** [comment]
> 传统模型可能得挑挑配置，效果一般都比较差 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Beyond ***@***.***&gt; 发送时间: 2023年9月9日 08:47 收件人: LibCity/Bigscity-LibCity ***@***.***&gt; 抄送: Jiawei Jiang ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [LibCity/Bigscity-LibCity] 关于传统模型 (Issue #356) 谢谢您的回复！ SVR的这个正常吗，数据集为PEMSD4，但是我发现80多的MAE高于其他论文报告的很多了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

最新一些sota模型还有在增加进libcity吗
