### ISSUE TITLE
请问test文件夹下提供的四个非深度学习模型ARIMA和SVR等能否修改为只预测PEMS数据集中的流量特征

### ISSUE THREAD

**Issue by Transformer0714** [LibCity/Bigscity-LibCity#360]
config中未发现有Outputdim参数的设置，非常感谢！

**Comment by Transformer0714** [comment]
使用ARIMA对PEMSD8进行预测时会出现报错：
ValueError: SARIMAX models require univariate `endog`. Got shape (12, 3).
（GPT对该错误的回答：该错误是由于使用 SARIMAX 模型时，输入的 endogenous 变量（即要预测的变量）是多变量的而不是单变量。SARIMAX 模型只能处理单变量的时间序列数据。）

**Comment by aptx1231** [comment]
不好意思，这个确实不支持一键配置。

https://github.com/LibCity/Bigscity-LibCity/blob/master/test/test_ARIMA.py#L52
修改data_col为你想要的列，比如traffic_flow.
这样就只读取流量特征，也就是只预测流量特征了。

**Comment by aptx1231** [comment]
或者说output_dim不支持配置，变成了data_col参数
