### ISSUE TITLE
How to train DCRNN, STGCN, MTGNN model use different datasets

### ISSUE THREAD

**Issue by tianshubao1** [LibCity/Bigscity-LibCity#361]
Dear Staff,

How are you? Hope you are doing well.

We are trying to use your methods (DCRNN, STGCN, MTGNN) as baselines in our proposed model. However, I found that your data are complied as a config file which is not easy to modify. We have the processed npy datasets and for the model training and testing. But we are not sure how to build a config file to make them compatible with the settings.

Thanks! Looking forward to your reply.

**Comment by aptx1231** [comment]
If it's a dataset of npy files, it's not complicated to modify, just change the places in traffic_state_dataset.py about reading files. But this may be difficult for those who are not familiar enough with the Libcity code, so I suggest using the atomic files we provide~.

**Comment by aptx1231** [comment]
https://github.com/LibCity/Bigscity-LibCity/blob/master/libcity/data/dataset/traffic_state_datatset.py#L238
This function is to convert the atomic file into an array in npy format, you can modify this function to read the npy file directly~

**Comment by tianshubao1** [comment]
Can I write something like this https://github.com/LibCity/Bigscity-LibCity-Datasets/blob/master/metr_la.py 
to convert the npy files into atomic files, and then let the model run atomic file directly? Would this be easier?

**Comment by aptx1231** [comment]
yes, you are right. atomic files are just csv format in fact. it is easy to convert npy to atomic files.

**Comment by tianshubao1** [comment]
One quick question, how to set the input_window and output_window to 1?

 I can't do it in cmd. I think maybe I can do it in config.json but I am not sure how to set it.

**Comment by aptx1231** [comment]
Yes，set it in the config.json&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Tianshu Bao ***@***.***&gt;
Date: Tue,Oct 17,2023 0:35 PM
To: LibCity/Bigscity-LibCity ***@***.***&gt;
Cc: Jiawei Jiang ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [LibCity/Bigscity-LibCity] How to train DCRNN, STGCN, MTGNN modeluse different datasets (Issue #361)





 
One quick question, how to set the input_window and output_window to 1?
 
I can't do it in cmd. I think maybe I can do it in config.json but I am not sure how to set it.

**Comment by tianshubao1** [comment]
Thanks, I've figured that out.
