### ISSUE TITLE
请问如何把评价指标MAPE调出来，现在显示的是inf

### ISSUE THREAD

**Issue by xnnnna** [LibCity/Bigscity-LibCity#362]

**Comment by aptx1231** [comment]
可以看Maksed mape指标，大部分论文都是看masked指标的，不管是mae me mape。
这是因为真实值有0。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xnnnna ***@***.***&gt;
发送时间: 2023年10月7日 20:31
收件人: LibCity/Bigscity-LibCity ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [LibCity/Bigscity-LibCity] 请问如何把评价指标MAPE调出来，现在显示的是inf (Issue #362)
