### ISSUE TITLE
针对PDFormer模型的相关问题

### ISSUE THREAD

**Issue by klayc-gzl** [LibCity/Bigscity-LibCity#363]
请问为什么我训练PEMS08那个数据集的时候一开始加载数据的shape在特征维度那块是9呢？train	x: (10700, 12, 170, 9), y: (10700, 12, 170, 9)

**Comment by aptx1231** [comment]
因为设置了add time in day（1维）和add day in week（7维），加上流量（1维）所以是9.

**Comment by klayc-gzl** [comment]
好的好的，谢谢您
