### ISSUE TITLE
关于ASTGCN模型运行PEMSD模型计算拉普拉斯矩阵时出现错误；

### ISSUE THREAD

**Issue by zhaozhihua97** [LibCity/Bigscity-LibCity#364]
![image](https://github.com/LibCity/Bigscity-LibCity/assets/50071503/b4027aa7-cd83-48a3-b963-c34e44f89c9c)
我看到了您之前的回复，针对这个问题，我尝试了修改LR为LM，尝试了将scipy的版本更换为您要求的1.5.3。但是都没有奏效，请问您在复现这个数据集指标时，有没有遇到这个问题，又是如何解决的呢？

**Comment by aptx1231** [comment]
这个没有遇到过哎
看了下之前的issue，设置"bidir_adj_mx": true 之后就没有这个问题了

**Comment by aptx1231** [comment]
可以换这个函数试试：https://github.com/LibCity/Bigscity-LibCity/blob/master/libcity/model/traffic_speed_prediction/DCRNN.py#L44

https://github.com/LibCity/Bigscity-LibCity/blob/master/libcity/model/traffic_speed_prediction/DCRNN.py#L49
