### ISSUE TITLE
关于如何用其它模型跑PDFormer中的grid-based dataset NYCTaxi的问题

### ISSUE THREAD

**Issue by evavaa** [LibCity/Bigscity-LibCity#365]
我看到您在PDFormer的文章中用很多模型在grid-based dataset上做了对比实验。我在尝试使用LibCity进行复现，但总是会有各种各样的报错，所以想请教一下用文章中的那些模型时，需要更改哪些地方的代码呢？数据集的config file是否也要有所更改？感谢！

**Comment by aptx1231** [comment]
你好呀。这个是比较简单的，可以看这个文档：https://bigscity-libcity-docs.readthedocs.io/en/latest/user_guide/data/dataset_for_task.html的Note 3. 介绍了如果把默认的point模型迁移到grid上边。本质上就是手动修改一下父类从TrafficStatePointDataset换成TrafficStateGridDataset，然后设置use_row_column是False。

欢迎star~

**Comment by aptx1231** [comment]
https://github.com/LibCity/Bigscity-LibCity/issues/368
