### ISSUE TITLE
PDFormer如何同时得到inflow和outflow的evaluation metrics

### ISSUE THREAD

**Issue by evavaa** [LibCity/Bigscity-LibCity#366]
我在用PDFormer跑NYCTaxi dataset时，得到的结果没有区分inflow和outflow。

<img width="531" alt="Screen Shot 2023-10-10 at 11 54 11 pm" src="https://github.com/LibCity/Bigscity-LibCity/assets/101331301/da51788a-474c-4196-b1c5-6308b6a7a982">

但是文章中有inflow和outflow分别的MAE、RMSE等结果，请问是如何做到的呢？

**Comment by aptx1231** [comment]
这个截图就是区分了的，0和1就是in和out呀~

另外，由于空间限制AAAI公开的文章目前只提供平均值了，不区分In和out。

arxiv版本还保留这个结果，感谢你还看我们的arxiv版本~

这个如果你还想要均值的话，可以直接修改traffic_state_evaluator的代码。

林外就是，PDFormer的问题可以在对应仓库提问，给那个仓库增加一下人气，谢谢~hh
