### ISSUE TITLE
原子文件可视化

### ISSUE THREAD

**Issue by klayc-gzl** [LibCity/Bigscity-LibCity#370]
我运行了可视化脚本，获得如下PeMS08的json文件，但是原始文件里面没有coordiantes，这个文件去哪能获取呢，这就不能进行可视化了吗？如果还可以的话，后续步骤是怎么样的呢？非常感谢您

![image](https://github.com/LibCity/Bigscity-LibCity/assets/80515849/640daf64-8ab2-4c52-a4fe-67ed4fa592bf)

**Comment by aptx1231** [comment]
这个原始数据就没经纬度，确实没法可视化了。
