### ISSUE TITLE
Hello author，I have some questions about libcity

### ISSUE THREAD

**Issue by ZPFPHD** [LibCity/Bigscity-LibCity#373]
请问运行完ARIMA，SVR模型，如何将结果和数据保存在libcity/cache？

**Comment by Kazeya27** [comment]
- 评估结果
main方法中evaluate_model的path可以选择保存路径
- 数据
  - 如果是指数据集，把每一轮得到trainx, trainy, testx, testy记录一下，最后
  np.savez_compressed(path,x_train=x_train,y_train=y_train,x_test=x_test,y_test=y_test)就可以
  - 如果是指模型，可以用pickle库
  with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)
