### ISSUE TITLE
libcity for pdformer

### ISSUE THREAD

**Issue by nana1223** [LibCity/Bigscity-LibCity#381]
您好，想请问下， libcity目前是否可以跑pdformer？还想请问下pdformer原论文是为了预测交通流量，用它预测交通需求量是否可行？

**Comment by Kazeya27** [comment]
@aptx1231

**Comment by NickHan-cs** [comment]
PDFormer还没有集成到LibCity中，但是PDFormer的开源代码https://github.com/BUAABIGSCity/PDFormer是基于LibCity的框架开发的。PDFormer也可以用于预测交通需求量。

**Comment by nana1223** [comment]
> PDFormer还没有集成到LibCity中，但是PDFormer的开源代码 https://github.com/BUAABIGSCity/PDFormer 是基于LibCity的框架开发的。PDFormer也可以用于预测交通需求量。

好的 感谢！
